apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: seismic-cloud
spec:
  environments:
    - name: dev
      build:
        from: master
    - name: prod
      build:
        from: release
  components:
    - name: core
      src: core
      ports:
        - name: http
          port: 80
      publicPort: http
      environmentConfig:
        - environment: prod
          replicas: 2
          monitoring: true
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '200m'
        - environment: dev
          replicas: 2
          monitoring: true
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '200m'
    - name: api
      src: api
      ports:
        - name: http
          port: 8080
      publicPort: http
      environmentConfig:
        - environment: dev
          variables:
            AUTHSERVER: 'https://login.microsoft.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0'
            HOST_ADDR: '0.0.0.0:8080'
            HTTP_ONLY: true
            STITCH_CMD: /usr/bin/cat
            SWAGGER: true
            ISSUER:  'https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0'
        - environment: prod
          replicas: 2
          variables:
            AUTHSERVER: 'https://login.microsoft.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0'
            HOST_ADDR: '0.0.0.0:8080'
            HTTP_ONLY: true
            STITCH_ADDR: core:5000
            SWAGGER: true
            ISSUER:  'https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0'
      secrets:
        - MANIFEST_DB_URI
  dnsAppAlias:
    environment: prod
    component: api
