apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: seismic-cloud-api
spec:
  environments:
    - name: dev
      build:
        from: master
    - name: prod
      build:
        from: v0.1.0

  components:
    - name: corestub
      src: corestub
      ports:
        - name: http
          port: 10000
      environmentConfig:
        - environment: prod
          replicas: 0
        - environment: dev
          replicas: 0
    - name: api
      src: api
      ports:
        - name: grpc
          port: 8080
      environmentConfig:
        - environment: prod
          replicas: 0
        - environment: dev
          replicas: 0
