apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: seismic-cloud
spec:
  environments:
    - name: dev
      build:
        from: master
    - name: prod
      build:
        from: release
    - name: monitor
      build:
        from: monitor
  components:
    - name: core
      src: core
      ports:
        - name: tcp
          port: 5000
      environmentConfig:
        - environment: prod
          replicas: 2
          monitoring: true
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '200m'
        - environment: dev
          replicas: 0
          monitoring: true
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '2048Mi'
              cpu: '200m'
        - environment: monitor
          monitoring: true
          
    - name: corestub
      src: corestub
      ports:
        - name: grpc
          port: 10000
      environmentConfig:
        - environment: prod
          replicas: 0
          monitoring: false
        - environment: dev
          replicas: 1
          monitoring: false
        - environment: monitor
          monitoring: false

    - name: api
      src: api
      secrets:
        - MANIFEST_DB_URI
        - AZURE_STORAGE_ACCESS_KEY
      ports:
        - name: http
          port: 8080
      publicPort: http
      environmentConfig:
        - environment: dev
          variables:
            AUTHSERVER: 'https://login.microsoft.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0'
            HOST_ADDR: '0.0.0.0:8080'
            HTTP_ONLY: true
            STITCH_GRPC_ADDR: 'corestub:10000'
            SWAGGER: true
            ISSUER: 'https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0'
            AZURE_STORAGE_ACCOUNT: 'seismiccloud'
            AZURE_CONTAINER_NAME: 'scblob'
        - environment: prod
          replicas: 2
          variables:
            AUTHSERVER: 'https://login.microsoft.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0'
            HOST_ADDR: '0.0.0.0:8080'
            HTTP_ONLY: true
            STITCH_ADDR: core:5000
            SWAGGER: true
            ISSUER: 'https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0'
        - environment: monitor
          variables:
            AUTHSERVER: 'https://login.microsoft.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0'
            HOST_ADDR: '0.0.0.0:8080'
            HTTP_ONLY: true
            STITCH_GRPC_ADDR: 'corestub:10000'
            SWAGGER: true
            ISSUER: 'https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0'

    - name: prometheus
      src: monitoring/prometheus
      ports:
        - name: http
          port: 9090
      publicPort: http
      environmentConfig:
        - environment: dev
          replicas: 0

    - name: grafana
      src: monitoring/grafana
      secrets:
        - GF_SECURITY_ADMIN_PASSWORD
      ports:
        - name: http
          port: 3000
      publicPort: http
      environmentConfig:
        - environment: dev
          replicas: 0

  dnsAppAlias:
    environment: prod
    component: api
